# Generated by Django 5.0.3 on 2024-03-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_daily', '0002_alter_reportdailyd_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdailyd',
            options={'verbose_name': 'Report daily dohod', 'verbose_name_plural': 'Report daily dohody'},
        ),
        migrations.AlterModelOptions(
            name='reportdailyr',
            options={'verbose_name': 'Report daily rashod', 'verbose_name_plural': 'Report daily rashody'},
        ),
    ]
