# Generated by Django 5.0.3 on 2024-03-30 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_d_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDailyD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=100)),
                ('how_much', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='report_daily_d', to='category.category')),
            ],
            options={
                'verbose_name': 'Report daily dohod',
                'verbose_name_plural': 'Report daily dohod',
            },
        ),
        migrations.CreateModel(
            name='ReportDailyR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=100)),
                ('how_much', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='report_daily_r', to='category.category')),
            ],
            options={
                'verbose_name': 'Report daily rashod',
                'verbose_name_plural': 'Report daily rashod',
            },
        ),
    ]
