# Generated by Django 5.1.5 on 2025-02-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_table_alter_category_d_table'),
        ('report', '0003_alter_reportdailyd_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportDailyR',
            new_name='ReportExpenses',
        ),
        migrations.RenameModel(
            old_name='ReportDailyD',
            new_name='ReportIncomes',
        ),
        migrations.AlterModelOptions(
            name='reportexpenses',
            options={'verbose_name': 'Report expense', 'verbose_name_plural': 'Report expenses'},
        ),
        migrations.AlterModelOptions(
            name='reportincomes',
            options={'verbose_name': 'Report income', 'verbose_name_plural': 'Report incomes'},
        ),
    ]
