# Generated by Django 5.1.5 on 2025-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_rename_reportdailyr_reportexpenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportincomes',
            name='body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
