# Generated by Django 5.1.5 on 2025-02-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reportincomes_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportexpenses',
            old_name='how_much',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='reportincomes',
            old_name='how_much',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='reportexpenses',
            name='body',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportincomes',
            name='body',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
