# Generated by Django 5.0.3 on 2024-03-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_d'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_d',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories_d'},
        ),
    ]
