# Generated by Django 5.0.3 on 2024-03-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_d_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_d',
            options={'verbose_name': 'category_d', 'verbose_name_plural': 'categories_d'},
        ),
    ]
