# Generated by Django 5.1.5 on 2025-02-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_d_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='category_d',
            table='category_d',
        ),
    ]
