# Generated by Django 5.1.5 on 2025-02-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_table_alter_category_d_table'),
        ('report', '0004_rename_reportdailyr_reportexpenses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryExpenses',
        ),
        migrations.RenameModel(
            old_name='Category_d',
            new_name='CategoryIncomes',
        ),
        migrations.AlterModelOptions(
            name='categoryexpenses',
            options={'verbose_name': 'category_expenses', 'verbose_name_plural': 'categories_expenses'},
        ),
        migrations.AlterModelOptions(
            name='categoryincomes',
            options={'verbose_name': 'category_incomes', 'verbose_name_plural': 'categories_incomes'},
        ),
        migrations.AlterModelTable(
            name='categoryexpenses',
            table='category_expenses',
        ),
        migrations.AlterModelTable(
            name='categoryincomes',
            table='category_incomes',
        ),
    ]
